### ISSUE TITLE
Problem when device orientation changes

### ISSUE THREAD

**Issue by Amol07** [ViccAlexander/Chameleon#22]
I've uploaded two images when the device orientation changes. The gradient does not work as it is expected. 

![ios simulator screen shot 27-mar-2015 11 22 30 pm](https://cloud.githubusercontent.com/assets/11028703/6873709/367ce45c-d4d8-11e4-883b-8dec24fc5cf1.png)
![ios simulator screen shot 27-mar-2015 11 22 41 pm](https://cloud.githubusercontent.com/assets/11028703/6873708/36783c9a-d4d8-11e4-8b36-ad0fa1a9e1dc.png)

**Comment by VAlexander** [comment]
@Amol07 The reason for this has to do with the way Chameleon generates a `gradientColor`. Every `gradientColor` is backed by a `CAGradientLayer`. Unfortunately what you are experiencing, is to be expected, since `CALayer` does not support layout managers on iOS, meaning it is up to you to calculate the frame changes yourself.

Side Note: My goal is to find a way for Chameleon to eventually handle all of this for you, but until then here's a quick solution for `gradientColor` and orientation changes if you're on iOS 8 and above.

Simply create a method where you update all of your objects background colors, which you plan on using a `gradientColor` for. This method will allow us to simplify our `gradientColor` code so we can set/update this from anywhere, anytime with one line of code.

``` objective-c
- (void) {
    
    self.view.backgroundColor = GradientColor(UIGradientStyleLeftToRight,
                                              self.view.frame,
                                              (@[FlatYellow, FlatRed]));
    
    self.innerView.backgroundColor = GradientColor(UIGradientStyleLeftToRight,
                                                   self.innerView.frame,
                                                   (@[FlatSkyBlue, FlatPurpleDark]));
}
```
Now, here's where the magic comes in. In order for the gradient color to reflect the new frame changes, we will need to know when an orientation transition is taking place. This is easy. If you're on iOS 8 simply do the following:

``` objective-c
- (void)viewWillTransitionToSize:(CGSize)size
       withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
    
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext> context) {

    } completion:^(id<UIViewControllerTransitionCoordinatorContext> context) {
        
        //This will update the frame of every view with a gradient color
        [self updateGradientColors];
    }];
    
    [super viewWillTransitionToSize:size withTransitionCoordinator: coordinator];
}
```

If you take a close look, you'll notice that on completion of the transition, we are calling our `updateGradientColors` method, which will use the new frames to reset the `gradientColors`. Now transitions will not be 100% smooth during rotation (unfortunately), but upon completion they should reflect the new frame changes.

![Example](http://i.imgur.com/JY845qv.gif)

**Comment by bre7** [comment]
@ViccAlexander [DLConstraintLayout](https://github.com/regexident/DLConstraintLayout) ?

**Comment by ViccAlexander** [comment]
@bre7 Interesting. I'll definitely look into it, thanks!
