### ISSUE TITLE
More Colors

### ISSUE THREAD

**Issue by bre7** [ViccAlexander/Chameleon#41]
? You can never have too many colors :grimacing::grimacing::grimacing:
* [flatuicolorpicker](http://www.flatuicolorpicker.com/all)
* [flatuicolors](https://flatuicolors.com/)
* [flatcolors](http://flatcolors.net/)

**Comment by ViccAlexander** [comment]
Awesome thinking @bre7. In fact, I've considered this before, but to be honest, more colors might not be as helpful as one may think. According to Hick's Law, if you increase the number of choices you are also increasing the amount of time it takes to make a decision. This is important to understand because what makes Chameleon useful is how convenient and quick it is to use. 

In 2.0, I've added the ability to import colors into a project by allowing developers to just know the hex code. If anything it might be more useful to allow a user to import their own colors easily, rather than hardcode them into the library myself. Let me think about this.

**Comment by bre7** [comment]
You have a good point, letting devs add their own colors is probably the best solution instead of adding colors to the palette. By the way Vic, is 2.0 going to be objc or swift ?

**Comment by ViccAlexander** [comment]
It's still going to be objective-c, but what I can do is probably drop it in beta as a branch, and if you have time you can try porting it to Swift entirely if you'd like? Would there be a bigger benefit to porting it over entirely, rather than what you've been doing at the moment? Just curious.

**Comment by bre7** [comment]
I'm no expert, but there are some benefits (structs, etc....) to using Swift. And also, imo at least, it's easier to maintain Swift code than OC...I have no problem in porting it to Swift in my spare time.

**Comment by ViccAlexander** [comment]
Oh cool. Yeah, I'm not as familiar with Swift syntax, as I am with Objective-C, which is why I defaulted to Obj-C, but if you don't mind helping to create a Swift version, I'm all for it. I'll probably create the 2.0 branch in the coming week or so.
