### ISSUE TITLE
NSInvalidArgumentException when using setGlobalThemeUsingPrimaryColor:withContentStyle:

### ISSUE THREAD

**Issue by caiotomazelli** [ViccAlexander/Chameleon#88]
I'm using iPhone 4S with iOS 7.1.1 installed. 

My app works fine on 4S simulator, but when I run it in the real device, it crashes with the following error: 

```Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Illegal property type, c for appearance setter, _installAppearanceSwizzlesForSetter:'```

When I remove setGlobalTheme, the app runs without problems.

It also works fine on a iPhone 5S with iOS 8.4.1 installed (real device).

Any hints on what may be causing the problem? I found related issues with the same error that pointed to disabling navBar translucence, but that didn't help me.

**Comment by caiotomazelli** [comment]
A heads-up: Updating to iOS 9.1 solved the problem on iPhone 4S. But the issue stands: shouldn't the framework be compatible with iOS 7+?

**Comment by bre7** [comment]
It *should*, some methods might not be fully compatible. Thanks for the report Caio, I'll check it out later today

**Comment by ViccAlexander** [comment]
@caiotomazelli Thanks for reporting the issue. After much thought, I think the best option for Chameleon would be to discontinue iOS 7 support. (If you'd like to use it on devices running iOS 7 you should downgrade to 1.2.1).

The reason this makes sense is because there should be no reason to support iOS 7, when all devices can and should be upgrading to the latest versions. According to Apple, **67%** of connected devices are currently running iOS 9, while **91%** are running iOS 8 and above. Unfortunately there doesn't seem to be a high enough demand to support earlier versions. However, if you'd like to continue supporting newer versions of Chameleon on iOS 7, you can definitely do so! Let us know and we'll link to your fork. Thanks for understanding.

[Apple Live Data](https://developer.apple.com/support/app-store/)

![screen shot 2015-11-25 at 10 49 14 pm](https://cloud.githubusercontent.com/assets/1724674/11416901/cbb735e2-93c6-11e5-80ec-5e242cc74f34.png)
